Encja User - implementacja
piotr-grosicki/project-jdp-2204-02 pull request #11
Opened 2022-04-04 17:37 UTC by aodzie

2022-04-05 22:45 UTC, piotr-grosicki requested changes

2022-04-05 22:45 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +public class User {
encja nie jest zgodna ze schematem bazy danych

2022-04-08 16:45 UTC, piotr-grosicki requested changes

2022-04-08 16:45 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private Long keyId;
tego troche nie rozumiem, co ma keyId z order wspolnego? :)

2022-04-08 22:11 UTC, Mc-Beton commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private Long keyId;
Mamy chyba źle opisany schemat bazy danych. Mamy tam klucz na Foreign Key.
Jak możemy inaczej opisać klucz autoryzacji?

2022-04-09 12:33 UTC, Mc-Beton approved these changes

2022-04-09 12:36 UTC, Grande17 approved these changes

2022-04-09 12:37 UTC, merged