BUILD: JDP220402-22
piotr-grosicki/project-jdp-2204-02 pull request #27
Opened 2022-04-12 17:14 UTC by rydzwr

2022-04-12 17:57 UTC, Grande17 commented
w Group domain dodal @AllArgsConstructor, jak zmieniasz coś w klasie to sprawdzaj czy testy przechodzą.

2022-04-12 17:59 UTC, Grande17 submitted a review, later dismissed

2022-04-12 17:59 UTC, Grande17 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>              mappedBy = "group",
Te zmiany powodują że w momencie usunięcia grupy skasujesz wszystkie produkty.

2022-04-12 17:59 UTC, Grande17 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> -
Dlaczego to usunąłeś?

2022-04-13 04:55 UTC, Mc-Beton commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTest.java
> +    @Id
Nie musisz wywoływać id w klasie testów. One są generowane w encji Group. Spróbuj stworzyć obiekt Group przez konstruktor, który zawiera w sobie tylko nazwę oraz opis tworzonej grupy, albo odtwórz poprzedni kod przez komendę git restore <path do tego pliku>.

2022-04-13 06:41 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTest.java
> +    @Id
dodatkowo te adnotacje totalnie nic nie robia w klasie testowej

2022-04-13 06:41 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTest.java
> +        Group g1 = new Group(groupId,"Desc");
tak jak wspomnialem na czacie, nie powinienes w ogole ustawiac groupId w encji. Konstruktor powinien umozliwiac utworzenie encji bez id

2022-04-13 06:42 UTC, piotr-grosicki commented on .gitignore
> +src/main/resources/application.properties
czemu ten plik zostal dodany do gitignore? w zadnym wypadku nie powinno go tutaj byc

2022-04-13 11:45 UTC, rydzwr commented
Dobra, ID z testów usunięte, application.properties dodałem do gitignore dlatego, że używam innych danych u siebie i myślałem, że ten plik będzie ignorowany tylko z mojego commita, a nie w całym projekcie. Usunąłem go z gitignore i poprostu nie załączę do nowego commita.

2022-04-13 11:48 UTC, piotr-grosicki commented
> Dobra, ID z testów usunięte, application.properties dodałem do gitignore dlatego, że używam innych danych u siebie i myślałem, że ten plik będzie ignorowany tylko z mojego commita, a nie w całym projekcie. Usunąłem go z gitignore i poprostu nie załączę do nowego commita.

wciaz nie przechodza testy `33 tests completed, 16 failed`

2022-04-13 11:52 UTC, rydzwr commented
> > Dobra, ID z testów usunięte, application.properties dodałem do gitignore dlatego, że używam innych danych u siebie i myślałem, że ten plik będzie ignorowany tylko z mojego commita, a nie w całym projekcie. Usunąłem go z gitignore i poprostu nie załączę do nowego commita.
> 
> wciaz nie przechodza testy `33 tests completed, 16 failed`

GroupRepository, wszystkie przechodzą, mam naprawiać też testy z innych zadań? Przecież order/userController nie są nawet napisane, to nie mogą przejść.

2022-04-13 11:54 UTC, piotr-grosicki commented
> 

to tak nie dziala. na branchy main wszystkie testy przechodza, na Twojej 16 nie przechodzi.

Czyli to zmiany u Ciebie na branchy powoduja ze testy przestaja przechodzic wiec musisz je poprawic inaczej nie bedzie sie dalo zmergowac Twoich zmian do maina

2022-04-13 12:26 UTC, piotr-grosicki commented
> > > Dobra, ID z testów usunięte, application.properties dodałem do gitignore dlatego, że używam innych danych u siebie i myślałem, że ten plik będzie ignorowany tylko z mojego commita, a nie w całym projekcie. Usunąłem go z gitignore i poprostu nie załączę do nowego commita.
> > 
> > 
> > wciaz nie przechodza testy `33 tests completed, 16 failed`
> 
> GroupRepository, wszystkie przechodzą, mam naprawiać też testy z innych zadań? Przecież order/userController nie są nawet napisane, to nie mogą przejść.

ogolnie sprawdzilem to wiekszosc testow nie przechodzi przez zmiany wersji, ktorych dokonales w `build.gradle`.  po przywroceniu build gradle do wersji z maina i zmianie `beforeEach` na `Before` w testach group nie przechodza tylko testy w product repository zwiazane ze zmianami w encji

2022-04-13 14:41 UTC, piotr-grosicki commented
> Wszystkie testy we wszystkich Controller'ach naprawione

wciaz sie nie buduje: 33 tests completed, 1 failed

2022-04-13 16:25 UTC, Mc-Beton commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +
Tu ponownie są zastosowane annotacje w konstruktorach, które nie są potrzebne, oraz posiadają niepotrzebną pozycję jak id podczas tworzenia nowego obiektu. Wystarczy jeden konstruktor z id do mapowania do OrderDto.

2022-04-13 16:41 UTC, Mc-Beton requested changes
Przy encji User brakuje nam annotacji @NotNull przy username i usersurname, oraz w konstruktorach brakuje pozycji userSurname.

2022-04-13 16:49 UTC, rydzwr commented
No rzeczywiście, wypadło mi z głowy, aby to dodać z powrotem

2022-04-13 17:14 UTC, Mc-Beton commented
Wszystko wygląda już dobrze, działa, tylko jedna ostatnia rzecz, która niestety prowadzi do poprawy 5 plików. Encja Groups oryginalnie była na dwóch zmiennych: nazwa grupy oraz opis grupy, a jest na tylko nazwa grupy. Możesz dopisać to jeszcze do Encji Groups (konstruktory się zmieniają), w GroupsDto, GroupsMapper i wtedy pozostaje wprowadzić te zmienną do testów w GroupRepositoryTests oraz ProductRepositoryTests? :)

2022-04-13 17:22 UTC, rydzwr commented
> Wszystko wygląda już dobrze, działa, tylko jedna ostatnia rzecz, która niestety prowadzi do poprawy 5 plików. Encja Groups oryginalnie była na dwóch zmiennych: nazwa grupy oraz opis grupy, a jest na tylko nazwa grupy. Możesz dopisać to jeszcze do Encji Groups (konstruktory się zmieniają), w GroupsDto, GroupsMapper i wtedy pozostaje wprowadzić te zmienną do testów w GroupRepositoryTests oraz ProductRepositoryTests? :)

Dobra, a tak myślę, że w sumie to też powinno być wtedy oznaczone jako @NotNull, przynajmniej nazwa. Nie chcemy przecież grupy bez nazwy chyba?

2022-04-13 17:27 UTC, Mc-Beton commented
> > Wszystko wygląda już dobrze, działa, tylko jedna ostatnia rzecz, która niestety prowadzi do poprawy 5 plików. Encja Groups oryginalnie była na dwóch zmiennych: nazwa grupy oraz opis grupy, a jest na tylko nazwa grupy. Możesz dopisać to jeszcze do Encji Groups (konstruktory się zmieniają), w GroupsDto, GroupsMapper i wtedy pozostaje wprowadzić te zmienną do testów w GroupRepositoryTests oraz ProductRepositoryTests? :)
> 
> Dobra, a tak myślę, że w sumie to też powinno być wtedy oznaczone jako @NotNull, przynajmniej nazwa. Nie chcemy przecież grupy bez nazwy chyba?

tak, jak najbardziej

2022-04-13 17:28 UTC, Mc-Beton commented
> > > Wszystko wygląda już dobrze, działa, tylko jedna ostatnia rzecz, która niestety prowadzi do poprawy 5 plików. Encja Groups oryginalnie była na dwóch zmiennych: nazwa grupy oraz opis grupy, a jest na tylko nazwa grupy. Możesz dopisać to jeszcze do Encji Groups (konstruktory się zmieniają), w GroupsDto, GroupsMapper i wtedy pozostaje wprowadzić te zmienną do testów w GroupRepositoryTests oraz ProductRepositoryTests? :)
> > 
> > 
> > Dobra, a tak myślę, że w sumie to też powinno być wtedy oznaczone jako @NotNull, przynajmniej nazwa. Nie chcemy przecież grupy bez nazwy chyba?
> 
> tak, jak najbardziej i też byłoby dobrze opis na @NotNull

2022-04-13 17:33 UTC, Mc-Beton approved these changes
Git!

2022-04-14 00:03 UTC, rydzwr commented
Dobra, poprawiłem konflikty, wszystko razem przechodzi teraz testy.
Jednego Commita nazwałem "X" - sprawdzałem coś, nie sądziłem, że to przejdzie - sorry
Czekam na review.

2022-04-14 00:19 UTC, merged