Jdp220402 4
piotr-grosicki/project-jdp-2204-02 pull request #3
Opened 2022-04-03 09:05 UTC by Mc-Beton

2022-04-03 09:12 UTC, piotr-grosicki requested changes
konflikty do rozwiazania: https://www.jetbrains.com/help/idea/resolve-conflicts.html

Konflikt rozwiązany

2022-04-03 14:40 UTC, Mc-Beton commented
Conflicts resolved

2022-04-04 07:07 UTC, piotr-grosicki requested changes

2022-04-04 07:07 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    public OrderDto getOrder(Long orderId) {
brakuje adnotacji `PathVariable`. w innych metodach rowniez

2022-04-04 07:36 UTC, Mc-Beton commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    public OrderDto getOrder(Long orderId) {
wprowadziłem odpowiednie adnotacje

2022-04-04 07:37 UTC, merged